"""reports: problem reports and found items

New reports module: `reports` (a student's problem report plus the triage agent's analysis),
`report_messages` (staff replies and student follow-ups) and `found_items` (lost and found,
with a text embedding for matching).

Revision ID: bbb63096dc6b
Revises: 9d3e5b7c1a2f
Create Date: 2026-10-02 21:12:33.221167
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'bbb63096dc6b'
down_revision: Union[str, None] = '9d3e5b7c1a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('found_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('bus_id', sa.Integer(), nullable=True),
    sa.Column('logged_by', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('unclaimed', 'matched', 'returned', name='found_item_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], name=op.f('fk_found_items_bus_id_buses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], name=op.f('fk_found_items_logged_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_found_items_trip_id_trips'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_found_items'))
    )
    op.create_index(op.f('ix_found_items_status'), 'found_items', ['status'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('stop_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('lateness', 'overcrowding', 'safety', 'lost_item', 'other', name='report_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('anonymous', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.Enum('open', 'replied', 'closed', name='report_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('severity', sa.Enum('low', 'normal', 'high', 'critical', name='report_severity', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('analysis_status', sa.Enum('pending', 'done', 'failed', name='analysis_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analysed_by', sa.String(length=64), nullable=True),
    sa.Column('analysed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('matched_found_item_id', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], name=op.f('fk_reports_closed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_found_item_id'], ['found_items.id'], name=op.f('fk_reports_matched_found_item_id_found_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_reports_route_id_routes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], name=op.f('fk_reports_stop_id_stops'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_reports_student_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_reports_trip_id_trips'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_analysis_status'), 'reports', ['analysis_status'], unique=False)
    op.create_index('ix_reports_status_created', 'reports', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_reports_student_id'), 'reports', ['student_id'], unique=False)
    op.create_table('report_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('from_staff', sa.Boolean(), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_report_messages_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_report_messages_report_id_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_messages'))
    )
    op.create_index(op.f('ix_report_messages_report_id'), 'report_messages', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_messages_report_id'), table_name='report_messages')
    op.drop_table('report_messages')
    op.drop_index(op.f('ix_reports_student_id'), table_name='reports')
    op.drop_index('ix_reports_status_created', table_name='reports')
    op.drop_index(op.f('ix_reports_analysis_status'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_found_items_status'), table_name='found_items')
    op.drop_table('found_items')
    # ### end Alembic commands ###
